language: java
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

install: true
script: mvn test
after_success:
  - mvn clean cobertura:cobertura coveralls:report

sudo: false
cache:
  directories:
    - $HOME/.m2